### ISSUE TITLE
Update category @ Django Packages / Feature Request

### ISSUE THREAD

**Issue by fredpalmer** [adamcharnock/django-su#31]
Just thought you may like to know your app is listed externally here:
https://www.djangopackages.com/packages/p/django-su/

However, there appears to be a more appropriate category and when searching for packages that provide similar functionality yours may not get evaluated:
https://www.djangopackages.com/grids/g/user-switching/

Since I already knew about and utilize your app, I thought you should know.  It's extremely useful.  I would also like to request one feature:

_Please allow the ability to enable staff users to impersonate users and/or the ability for a super-user to assign the permission to staff user to impersonate a user._

**Comment by bashu** [comment]
Hey,

check this https://github.com/adamcharnock/django-su/blob/develop/example/utils.py#L3
and this: https://github.com/adamcharnock/django-su/blob/develop/example/settings.py#L105

**Comment by bashu** [comment]
done!
