### ISSUE TITLE
Logging in as a user shouldn't change the user's `last_login` timestamp

### ISSUE THREAD

**Issue by adamcharnock** [adamcharnock/django-su#40]
This happens when we call Django's `login()` function, which triggers the `user_logged_in` signal. This in turn triggers django's `update_last_login()`.

The only obvious way I can see to achieve this is to change the `last_login` value back after it has been set, but this does not feel ideal. Better suggestions welcome!

**Comment by bashu** [comment]
Can be achieved by using custom login function...

**Comment by bashu** [comment]
I am idiot, we have ``SU_CUSTOM_LOGIN_ACTION`` for it...

**Comment by bashu** [comment]
@adamcharnock check this https://github.com/adamcharnock/django-su/blob/develop/example/utils.py#L25

**Comment by adamcharnock** [comment]
Hey @bashu! I've been thinking about this and I think that `last_login` shouldn't be updated by default (as the user didn't login, after all).

I've therefore submitted PR #42, let me know what you think

**Comment by bashu** [comment]
should be fixed
