### ISSUE TITLE
Order user dropdown alphabetically

### ISSUE THREAD

**Issue by adamcharnock** [adamcharnock/django-su#41]
The user selection drop-down in the admin UI shows unordered users, which makes it hard to find the desired user in the list.

**Comment by adamcharnock** [comment]
@bashu A client just flagged this to me so thought I'd sort it out. There seem to have been a fair few commits since the last release, are we ok to do another release?

**Comment by bashu** [comment]
@bashu yep we are ok :+1:

**Comment by bashu** [comment]
should be fixed
