### ISSUE TITLE
Breaks user admin in django-suit

### ISSUE THREAD

**Issue by paketep** [adamcharnock/django-su#48]
Hi!.

Great work with the plugin, it's really useful.

However, it looks like it doesn't like to work with django-suit. "Login as" works ok in the changelist, but it breaks completely the user form in the admin.

Thanks!

**Comment by bashu** [comment]
@paketep please try ``pip install -U django-su``

**Comment by paketep** [comment]
Thanks, bashu.

I'm out of the office for Easter, but I'll test your fix as soon as I get back on Tuesday.

Have a nice week!

**Comment by paketep** [comment]
Hi, bashu!

Sorry it took me a bit more to test your changes.

User admin page now looks great and works great as well. In the beginning it was deleting my session, but I think it was because I didn't remove 0.5.0 before installing 0.5.1.

However, now selecting a user in the /su/login page gives me a CSRF error. It was working ok with 0.5.0 (which I reinstalled to be sure).

Also, I don't know why, the "Login as another user" button in that page looks different because the anchor tag is inside a List Item. I don't know if there's a way to fix that in the plug-in or if I should retouch the template. Here's a screenshot:

![051a](https://cloud.githubusercontent.com/assets/700473/14143620/8e83452a-f68c-11e5-9e4d-2096a878f605.png)

**Comment by bashu** [comment]
see https://github.com/darklow/django-suit/pull/499, in a meantime you can override ``su/login_link.html`` template

**Comment by paketep** [comment]
Great, I put the template in my app while I wait for suit's next version, and now it looks perfect.

Thank you!
