### ISSUE TITLE
Support for string view arguments is deprecated

### ISSUE THREAD

**Issue by matheusjardimb** [adamcharnock/django-su#49]
According to logs (running with Django 1.9.4):
`django_su/urls.py:10: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got su_logout). Pass the callable instead.`

**Comment by bashu** [comment]
see https://github.com/adamcharnock/django-su/issues/46

**Comment by matheusjardimb** [comment]
Sorry @bashu but I didn't get it. The issue is still happening with 0.5.0. 
Why are #48 and #49 closed?

**Comment by matheusjardimb** [comment]
Hello @bashu !

I didn't get why you closed this issue. The warning is still happening in version 0.5.0.
Was it fixed but new version wasn't released?

Thanks!

**Comment by bashu** [comment]
@matheusjardimb please try ``pip install -U django-su``

**Comment by matheusjardimb** [comment]
Tks! Now I'm running with version 0.5.1 and the issue got solved ;)

**Comment by bashu** [comment]
de nada! =)
