### ISSUE TITLE
A couple of quick suggestions

### ISSUE THREAD

**Issue by paketep** [adamcharnock/django-su#50]
Hello!.

A couple of quick suggestions for the module, hoping you guys like them:
- Combo/Autocomplete selector: since many times user logins are dictated by ids, or national id, or whatever, add Name and Surname both in the displayed options and as searchable strings for the ajax selects, i.e., instead of user "100000065" show "100000065 (Pepe Pérez)".
- Add a link to stop _su_ing a user, perhaps one besides "change password" and "logout". Another alternative could be showing the user being _su_ed and the real user in brackets, and clicking in the real user login would bring you back to your own profile. Example: "Welcome, 100000065 [pperez]"

Thank you, and again, great work!

**Comment by bashu** [comment]
1) see https://github.com/adamcharnock/django-su/blob/develop/example/lookups.py as example and related settings https://github.com/adamcharnock/django-su/blob/develop/example/settings.py#L151

refer to http://django-ajax-selects.readthedocs.org for more details

**Comment by bashu** [comment]
2) make sure ``django_su.context_processors.is_su`` is enabled, then customize ``admin\base.html`` either ``welcome-msg`` block or ``userlinks`` block, for example
```html+django
{% block userlinks %}
    {% url 'django-admindocs-docroot' as docsroot %}
    {% if docsroot %}
        <a href="{{ docsroot }}">{% trans 'Documentation' %}</a> /
    {% endif %}
    {% if user.has_usable_password %}
    <a href="{% url 'admin:password_change' %}">{% trans 'Change password' %}</a> /
    {% endif %}
    {% if IS_SU %}
    <a href="{% url 'su_logout' %}">{% trans 'Log out' %}</a>
    {% else %}
    <a href="{% url 'admin:logout' %}">{% trans 'Log out' %}</a>
    {% endif %}
{% endblock %}

```

**Comment by adamcharnock** [comment]
It is been a while since there was any activity here so I'm going to close this. However, feel free to reopen if you come back to it or more discussion is needed. #housekeepingday
