### ISSUE TITLE
CSRF error when selecting user in /su/login

### ISSUE THREAD

**Issue by paketep** [adamcharnock/django-su#51]
Couldn't reopen issue #48, so I'll copy and paste here:

> Hi, bashu!
> 
> Sorry it took me a bit more to test your changes.
> 
> User admin page now looks great and works great as well. In the beginning it was deleting my session, but I think it was because I didn't remove 0.5.0 before installing 0.5.1.
> 
> However, now selecting a user in the /su/login page gives me a CSRF error. It was working ok with 0.5.0 (which I reinstalled to be sure).
> 
> Also, I don't know why, the "Login as another user" button in that page looks different because the anchor tag is inside a List Item. I don't know if there's a way to fix that in the plug-in or if I should retouch the template. Here's a screenshot:
> 
> ![8e83452a-f68c-11e5-9e4d-2096a878f605](https://cloud.githubusercontent.com/assets/700473/14240788/d8ef5306-fa47-11e5-82ab-64dbcc55ad8f.png)

Thank you!

**Comment by bashu** [comment]
Try ``pip install -U django-su``

**Comment by paketep** [comment]
Working perfectly now, thank you!
