### ISSUE TITLE
Customize presentation of text on the admin site

### ISSUE THREAD

**Issue by Gustavosdo** [adamcharnock/django-su#54]
I am using django-suit.
I made a small change in my base_site.html (extended) file to set the text display otherwise to the accessed user.

<img width="337" alt="admin_user_1" src="https://cloud.githubusercontent.com/assets/2745118/14763553/1aba50fc-096f-11e6-9c6a-33b785b8536e.png">
After access:
<img width="378" alt="admin_user_2" src="https://cloud.githubusercontent.com/assets/2745118/14763582/bdf16102-096f-11e6-9a48-d27b82436e59.png">

The code:

    {% block welcome-msg %}
      {% if IS_SU %}
        <a href="/su/" title="{% trans 'Restabelecer papel original' %}">{% trans 'Você' %}</a>{% trans ' acessou como,' %}
      {% else %}
        {% trans 'Welcome,' %}
      {% endif %}
      <strong>
        {% filter force_escape %}
          {% firstof user.first_name user.username %}
        {% endfilter %}
      </strong>.
    {% endblock %}

**Comment by bashu** [comment]
nice!! in English?

**Comment by Gustavosdo** [comment]
Hello @bashu,

I just saw your message now.
I forgot to change the example to English. Sorry.

I think that's a more elegant solution to alert when access is performed as another user ... Anyway, I wanted to share the idea.

Thanks for updating the repository with the sample  :)
