### ISSUE TITLE
Only admin can login with other user credentials?

### ISSUE THREAD

**Issue by Allan-Nava** [adamcharnock/django-su#58]
Hi,

I need a feature like Netflix users management, that one users can impersonate the "children"

Thanks for support!

**Comment by adamcharnock** [comment]
Hi Allan,

I’m not familiar with this feature, could you describe it in more detail?

I’m happy to accept pull requests, but I don’t have time to do fresh
development at the moment. So the implementation will be dependent on 1)
someone contributing it, 2) me or my work having need of it.

However, it is quite possible that django-su can provide what you need in
its current form. If you describe it then I may be able to point you in the
right direction.

Adam

**Comment by Allan-Nava** [comment]
Hi @adamcharnock ,

Is possibile to manage the users inside the main user?

Such as the netflix feature where there is a only 1 one account that can handle and manage the 4 "childrens"

**Comment by adamcharnock** [comment]
Ah, I see, thank you.

Django su doesn’t have this feature, and I think it probably doesn’t fit
into Django-su’s featureset set either.

If you were to create this yourself in your own app then Django-su would
allow you to switch between users. But you would have to build the child
user feature on your side.

Adam

Closes 58
