### ISSUE TITLE
Any chance of a new version on pypi?

### ISSUE THREAD

**Issue by hmpf** [adamcharnock/django-su#67]
I prefer installing from pypi. Version 0.8 does what I need, but I no longer have any django projects that use anything older than Django 1.11. It'd be nice to have a version that explicitly supports 1.11 and pythons newer than 3.4, which is after all end-of-lifed. When 1.11 is eol, another version that officially does not support python 2 would also be appreciated.

**Comment by bashu** [comment]
@hmpf any problems with Django 2+ or python > 3.4

**Comment by hmpf** [comment]
I don't have anything needing su on Django 2+ yet, that's a high priority task for the coming spring, will aim for 2.2. I'll test on d1.11/p3.7 though.

**Comment by adamcharnock** [comment]
I've just released 0.9.0 which includes Django 1.11 & 2 & 3 support, and Python upto and including 3.8. A big thank you to @hamstamp85 and @gengue for submitting PRs for this.
